In [2]:
import matplotlib.pyplot as plt
from tqdm import tqdm
import pandas as pd
import numpy as np
import os

data_path = "C:/Users/mhals/Appdata/Local/Programs/Programming/GitHub/Phys117/Markus/Pandas_analysis/Subplots/Hub/XGBoost/CSVData/"
data_files = [data_path + data_file for data_file in os.listdir(data_path)]
folders = ["Background", "BH", "Sphaleron"]
stuffs = ["electron", "jet", "MET", "muon", "photon", "tau"]
file_amounts = [2, 18, 3]


folder_dataframes = []
for folder in folders:
    dataframes = []
    data_files = [data_path + folder + "/" + data_file for data_file in os.listdir(data_path + folder)]
    for data_file in data_files:
        data = pd.read_csv(data_file)
        data = data.drop("Unnamed: 0", axis = 1)
        print(data.iloc[:])
        dataframes.append(data)
    folder_dataframes.append(dataframes)

                                      electron0  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                      electron1  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                                    jet0  \
0      ('jet', 0.969, -1.139, 162.24, 8.8, 9.0, 0.0, ...
1      ('jet', 1.059, -2.772, 178.28, 18.7, 9.0, 0.0,...
2      ('jet', -0.711, 1.838, 117.29, 22.09, 13.0, 0....
3      ('jet', 0.144, -0.952, 111.07, 10.64, 6.0, 1.0...
4      ('jet', -0.763, -2.705, 192.49, 24.87, 18.0, 1...
...                                                  ...
99995  ('jet', -0.182, 1.105, 132.45, 32.02, 9.0, 1.0...
99996  ('jet', -0.426, 0.87, 90.88, 6.32, 6.0, 0.0, 0...
99997  ('jet', 0.795, -0.864, 112.46, 17.25, 9.0, 0.0...
99998  ('jet', 0.249, -2.47, 248.09, 38.32, 23.0, 0.0...
99999  ('jet', -1.051, 2.667, 92.04, 13.75, 10.0, 1.0...

                                                    jet1  \
0      ('jet', 2.4, 1.948, 80.95, 13.42, 5.0, 0.0, 1.06)
1      ('jet', 1.842, 0.817, 148.92, 24.08, 17.0, 1.0...
2      ('jet', 0.569, -0.526, 80.01, 12.94, 13.0, 0.0...
3      ('jet', -0.762, 2.217, 104.43, 11.72, 8.0, 0.0...
4      ('jet', -1.583, 0.286, 74.59, 9.68, 5.0, 0.0, ...
...                                                  ...
99995  ('jet', 0.897, -1.464, 64.01, 15.85, 4.0, 0.0,...
99996  ('jet', -0.264, -0.938, 64.04, 9.3, 6.0, 1.0, ...
99997  ('jet', 0.228, 2.029, 94.34, 10.24, 9.0, 0.0, ...
99998  ('jet', 0.383, 0.644, 125.94, 18.02, 14.0, 0.0...
99999  ('jet', -0.132, -0.084, 91.73, 5.48, 3.0, 0.0,...

                                                    jet2  \
0      ('jet', 3.035, 1.661, 79.74, 15.8, 0.0, 0.0, 3.3)
1      ('jet', 0.6, -2.092, 114.67, 14.01, 13.0, 0.0,...
2      ('jet', 1.783, -1.86, 67.09, 3.81, 2.0, 0.0, 0.0)
3      ('jet', -0.195, -2.325, 57.76, 15.67, 15.0, 1....
4      ('jet', 1.721, 0.68, 72.38, 19.51, 16.0, 0.0, ...
...                                                  ...
99995  ('jet', 0.647, -2.241, 49.1, 9.99, 9.0, 0.0, 0...
99996  ('jet', 0.004, 2.71, 60.27, 8.19, 7.0, 0.0, 0.85)
99997  ('jet', 1.636, 2.698, 78.45, 15.71, 12.0, 1.0,...
99998  ('jet', 1.744, 1.379, 76.58, 15.62, 10.0, 0.0,...
99999  ('jet', -0.344, -1.398, 52.99, 7.67, 10.0, 0.0...

                                                    jet3  \
0      ('jet', 2.293, -2.515, 69.75, 12.21, 6.0, 1.0,...
1      ('jet', 1.681, 0.084, 75.09, 9.31, 7.0, 0.0, 0.0)
2      ('jet', -0.232, 0.066, 54.74, 8.2, 4.0, 0.0, 0...
3      ('jet', -1.265, 1.591, 41.4, 16.05, 9.0, 0.0, ...
4      ('jet', 0.499, -2.063, 60.94, 12.43, 12.0, 0.0...
...                                                  ...
99995  ('jet', -1.127, 2.84, 26.95, 6.01, 2.0, 0.0, 2...
99996  ('jet', 0.848, 0.899, 26.41, 5.96, 5.0, 0.0, 0.0)
99997  ('jet', -0.12, -1.381, 48.35, 8.78, 9.0, 0.0, ...
99998  ('jet', 0.095, -1.367, 38.13, 5.93, 4.0, 0.0, ...
99999  ('jet', -0.278, -2.382, 52.22, 15.77, 13.0, 1....

                                                    jet4  \
0      ('jet', 1.149, 0.129, 33.05, 4.07, 3.0, 0.0, 1...
1      ('jet', 1.168, 0.571, 38.32, 5.18, 12.0, 0.0, ...
2      ('jet', -2.436, 1.459, 42.36, 7.69, 5.0, 1.0, ...
3       ('jet', 1.51, 2.301, 41.05, 7.1, 5.0, 0.0, 8.04)
4      ('jet', 0.034, -0.532, 46.18, 8.46, 7.0, 0.0, ...
...                                                  ...
99995           [nan, nan, nan, nan, nan, nan, nan, nan]
99996           [nan, nan, nan, nan, nan, nan, nan, nan]
99997  ('jet', -3.347, 2.906, 44.03, 7.45, 0.0, 0.0, ...
99998  ('jet', -0.588, 0.504, 28.06, 7.35, 8.0, 0.0, ...
99999  ('jet', -0.816, 1.218, 45.85, 10.98, 6.0, 1.0,...

                                                    jet5  \
0               [nan, nan, nan, nan, nan, nan, nan, nan]
1       ('jet', 0.269, 1.864, 27.19, 7.3, 9.0, 0.0, 0.0)
2      ('jet', -1.39, -2.582, 39.43, 14.32, 6.0, 0.0,...
3      ('jet', -0.07, 1.015, 27.27, 6.27, 5.0, 0.0, 0.0)
4      ('jet', -0.813, -0.227, 37.01, 6.94, 5.0, 0.0,...
...                                                  ...
99995           [nan, nan, nan, nan, nan, nan, nan, nan]
99996           [nan, nan, nan, nan, nan, nan, nan, nan]
99997  ('jet', 1.185, 0.623, 36.06, 4.98, 6.0, 1.0, 0...
99998           [nan, nan, nan, nan, nan, nan, nan, nan]
99999  ('jet', -0.693, -1.778, 36.46, 5.22, 10.0, 0.0...

                                                    jet6  \
0               [nan, nan, nan, nan, nan, nan, nan, nan]
1               [nan, nan, nan, nan, nan, nan, nan, nan]
2      ('jet', 1.686, 2.929, 28.79, 7.89, 7.0, 0.0, 0...
3               [nan, nan, nan, nan, nan, nan, nan, nan]
4      ('jet', -3.307, -0.23, 27.1, 5.99, 0.0, 0.0, 1...
...                                                  ...
99995           [nan, nan, nan, nan, nan, nan, nan, nan]
99996           [nan, nan, nan, nan, nan, nan, nan, nan]
99997  ('jet', 1.06, -0.244, 24.49, 5.0, 3.0, 0.0, 0.15)
99998           [nan, nan, nan, nan, nan, nan, nan, nan]
99999           [nan, nan, nan, nan, nan, nan, nan, nan]

                                           jet7  ...  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]  ...
1      [nan, nan, nan, nan, nan, nan, nan, nan]  ...
2      [nan, nan, nan, nan, nan, nan, nan, nan]  ...
3      [nan, nan, nan, nan, nan, nan, nan, nan]  ...
4      [nan, nan, nan, nan, nan, nan, nan, nan]  ...
...                                         ...  ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]  ...
99996  [nan, nan, nan, nan, nan, nan, nan, nan]  ...
99997  [nan, nan, nan, nan, nan, nan, nan, nan]  ...
99998  [nan, nan, nan, nan, nan, nan, nan, nan]  ...
99999  [nan, nan, nan, nan, nan, nan, nan, nan]  ...

                                                  MET0  \
0       ('MET', 0.0, 1.564, 49.99, 0.0, 0.0, 0.0, 0.0)
1      ('MET', 0.0, -0.193, 17.38, 0.0, 0.0, 0.0, 0.0)
2      ('MET', 0.0, -1.819, 41.24, 0.0, 0.0, 0.0, 0.0)
3      ('MET', 0.0, -1.508, 43.67, 0.0, 0.0, 0.0, 0.0)
4         ('MET', 0.0, 1.4, 19.56, 0.0, 0.0, 0.0, 0.0)
...                                                ...
99995  ('MET', 0.0, -2.083, 26.82, 0.0, 0.0, 0.0, 0.0)
99996  ('MET', 0.0, -1.585, 37.46, 0.0, 0.0, 0.0, 0.0)
99997  ('MET', 0.0, -0.668, 25.35, 0.0, 0.0, 0.0, 0.0)
99998  ('MET', 0.0, -0.016, 43.15, 0.0, 0.0, 0.0, 0.0)
99999   ('MET', 0.0, 2.169, 23.55, 0.0, 0.0, 0.0, 0.0)

                                                   muon0  \
0               [nan, nan, nan, nan, nan, nan, nan, nan]
1               [nan, nan, nan, nan, nan, nan, nan, nan]
2               [nan, nan, nan, nan, nan, nan, nan, nan]
3      ('muon', -0.106, -0.064, 21.16, 0.11, 1.0, 2.0...
4      ('muon', -0.965, 1.23, 27.31, 0.11, 1.0, 4.0, ...
...                                                  ...
99995           [nan, nan, nan, nan, nan, nan, nan, nan]
99996  ('muon', -0.796, -2.776, 61.25, 0.11, -1.0, 4....
99997           [nan, nan, nan, nan, nan, nan, nan, nan]
99998           [nan, nan, nan, nan, nan, nan, nan, nan]
99999           [nan, nan, nan, nan, nan, nan, nan, nan]

                                          muon1  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                          muon2  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                        photon0  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                        photon1  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                                    tau0  \
0               [nan, nan, nan, nan, nan, nan, nan, nan]
1               [nan, nan, nan, nan, nan, nan, nan, nan]
2               [nan, nan, nan, nan, nan, nan, nan, nan]
3               [nan, nan, nan, nan, nan, nan, nan, nan]
4      ('tau', -0.261, 1.939, 70.17, 11.85, 1.0, 0.0,...
...                                                  ...
99995           [nan, nan, nan, nan, nan, nan, nan, nan]
99996           [nan, nan, nan, nan, nan, nan, nan, nan]
99997           [nan, nan, nan, nan, nan, nan, nan, nan]
99998           [nan, nan, nan, nan, nan, nan, nan, nan]
99999           [nan, nan, nan, nan, nan, nan, nan, nan]

                                           tau1  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                           tau2 datasets
0      [nan, nan, nan, nan, nan, nan, nan, nan]        0
1      [nan, nan, nan, nan, nan, nan, nan, nan]        0
2      [nan, nan, nan, nan, nan, nan, nan, nan]        0
3      [nan, nan, nan, nan, nan, nan, nan, nan]        0
4      [nan, nan, nan, nan, nan, nan, nan, nan]        0
...                                         ...      ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]        0
99996  [nan, nan, nan, nan, nan, nan, nan, nan]        0
99997  [nan, nan, nan, nan, nan, nan, nan, nan]        0
99998  [nan, nan, nan, nan, nan, nan, nan, nan]        0
99999  [nan, nan, nan, nan, nan, nan, nan, nan]        0

[100000 rows x 27 columns]
                                               electron0  \
0               [nan, nan, nan, nan, nan, nan, nan, nan]
1               [nan, nan, nan, nan, nan, nan, nan, nan]
2               [nan, nan, nan, nan, nan, nan, nan, nan]
3               [nan, nan, nan, nan, nan, nan, nan, nan]
4               [nan, nan, nan, nan, nan, nan, nan, nan]
...                                                  ...
99995           [nan, nan, nan, nan, nan, nan, nan, nan]
99996           [nan, nan, nan, nan, nan, nan, nan, nan]
99997           [nan, nan, nan, nan, nan, nan, nan, nan]
99998  ('electron', -0.338, -0.328, 20.85, 0.0, -1.0,...
99999           [nan, nan, nan, nan, nan, nan, nan, nan]

                                      electron1  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                      electron2  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                                    jet0  \
0      ('jet', 0.259, 2.156, 508.13, 69.55, 21.0, 0.0...
1      ('jet', 0.223, 2.359, 416.53, 70.5, 15.0, 0.0,...
2      ('jet', 0.023, -1.971, 640.75, 178.08, 32.0, 1...
3      ('jet', 0.987, -1.148, 623.93, 77.97, 19.0, 0....
4      ('jet', 0.757, 1.106, 501.74, 85.31, 21.0, 0.0...
...                                                  ...
99995  ('jet', 0.864, 0.587, 400.9, 102.9, 20.0, 1.0,...
99996  ('jet', 0.179, 3.016, 450.7, 90.85, 22.0, 1.0,...
99997  ('jet', 0.535, -0.647, 730.07, 114.6, 25.0, 0....
99998  ('jet', 0.24, 2.408, 510.95, 84.45, 16.0, 1.0,...
99999  ('jet', -0.533, -2.768, 509.17, 80.88, 23.0, 0...

                                                    jet1  \
0      ('jet', 0.582, -1.376, 432.89, 118.67, 29.0, 1...
1      ('jet', -2.335, -0.976, 141.2, 7.61, 3.0, 0.0,...
2      ('jet', -1.294, 0.109, 220.59, 38.07, 23.0, 1....
3      ('jet', -0.03, 2.18, 268.92, 17.01, 15.0, 0.0,...
4      ('jet', 1.846, -1.848, 438.96, 109.97, 26.0, 0...
...                                                  ...
99995  ('jet', -0.761, -2.612, 214.7, 35.28, 23.0, 1....
99996  ('jet', 0.168, 0.277, 392.62, 61.75, 12.0, 1.0...
99997  ('jet', 0.483, 2.517, 692.1, 150.31, 22.0, 1.0...
99998  ('jet', 0.302, -0.906, 245.28, 12.17, 11.0, 0....
99999  ('jet', -1.27, 2.388, 191.96, 51.83, 29.0, 0.0...

                                                    jet2  \
0      ('jet', 3.799, 0.54, 117.8, 32.82, 0.0, 0.0, 4...
1      ('jet', -1.635, -0.551, 52.65, 11.53, 8.0, 1.0...
2      ('jet', -1.227, 1.044, 98.17, 19.29, 17.0, 0.0...
3      ('jet', 1.862, 0.212, 93.23, 21.95, 20.0, 0.0,...
4      ('jet', 1.901, -2.497, 101.71, 14.66, 21.0, 0....
...                                                  ...
99995  ('jet', -0.541, -2.09, 171.77, 29.77, 23.0, 0....
99996  ('jet', -0.963, 2.558, 87.26, 9.33, 5.0, 0.0, ...
99997  ('jet', 0.63, -0.03, 100.28, 6.76, 7.0, 0.0, 9...
99998  ('jet', 3.039, 2.71, 141.87, 19.72, 0.0, 0.0, ...
99999  ('jet', -1.292, 0.689, 93.22, 16.91, 12.0, 0.0...

                                                    jet3  \
0      ('jet', 0.115, -0.885, 116.66, 10.12, 11.0, 0....
1      ('jet', 1.032, 1.609, 31.99, 4.71, 1.0, 1.0, 0.0)
2      ('jet', 0.791, 2.273, 42.46, 8.61, 9.0, 0.0, 0...
3      ('jet', 1.547, -1.382, 57.9, 12.85, 20.0, 1.0,...
4      ('jet', 0.355, 1.715, 90.14, 15.77, 24.0, 1.0,...
...                                                  ...
99995  ('jet', 0.604, -1.953, 113.35, 11.43, 9.0, 0.0...
99996  ('jet', 0.155, 0.987, 69.82, 8.86, 10.0, 0.0, ...
99997  ('jet', 0.415, 3.06, 32.68, 4.82, 16.0, 0.0, 0.0)
99998  ('jet', 0.903, 2.215, 61.31, 7.36, 7.0, 0.0, 3...
99999  ('jet', -0.858, -2.251, 91.92, 17.2, 19.0, 0.0...

                                                    jet4  \
0      ('jet', 1.46, -0.502, 78.11, -0.0, 1.0, 0.0, 0.0)
1               [nan, nan, nan, nan, nan, nan, nan, nan]
2      ('jet', 1.516, 1.125, 22.86, 5.07, 5.0, 0.0, 0...
3      ('jet', -0.081, -0.162, 47.1, 9.27, 11.0, 0.0,...
4               [nan, nan, nan, nan, nan, nan, nan, nan]
...                                                  ...
99995  ('jet', -0.426, -3.068, 103.86, 10.34, 15.0, 1...
99996  ('jet', 0.902, 2.84, 40.19, 7.17, 8.0, 0.0, 0.19)
99997  ('jet', -0.622, -2.005, 25.76, 5.02, 2.0, 0.0,...
99998  ('jet', 2.097, 2.279, 59.44, 14.03, 10.0, 0.0,...
99999  ('jet', -1.305, -3.059, 86.26, 26.49, 23.0, 1....

                                                    jet5  \
0      ('jet', -0.747, -2.546, 30.75, 8.88, 7.0, 0.0,...
1               [nan, nan, nan, nan, nan, nan, nan, nan]
2               [nan, nan, nan, nan, nan, nan, nan, nan]
3      ('jet', 0.187, -2.558, 42.12, 9.7, 8.0, 0.0, 9...
4               [nan, nan, nan, nan, nan, nan, nan, nan]
...                                                  ...
99995  ('jet', 0.061, 2.521, 101.46, 13.38, 5.0, 0.0,...
99996           [nan, nan, nan, nan, nan, nan, nan, nan]
99997           [nan, nan, nan, nan, nan, nan, nan, nan]
99998  ('jet', 1.316, -3.073, 57.54, 11.79, 6.0, 1.0,...
99999  ('jet', 0.265, 0.027, 44.46, 7.39, 5.0, 0.0, 0...

                                                    jet6  ...  \
0               [nan, nan, nan, nan, nan, nan, nan, nan]  ...
1               [nan, nan, nan, nan, nan, nan, nan, nan]  ...
2               [nan, nan, nan, nan, nan, nan, nan, nan]  ...
3       ('jet', 1.1, 0.546, 23.16, 8.97, 4.0, 0.0, 1.53)  ...
4               [nan, nan, nan, nan, nan, nan, nan, nan]  ...
...                                                  ...  ...
99995  ('jet', 0.495, -2.896, 100.67, 14.67, 10.0, 0....  ...
99996           [nan, nan, nan, nan, nan, nan, nan, nan]  ...
99997           [nan, nan, nan, nan, nan, nan, nan, nan]  ...
99998           [nan, nan, nan, nan, nan, nan, nan, nan]  ...
99999  ('jet', -2.016, 1.253, 22.37, 8.68, 7.0, 0.0, ...  ...

                                          muon2  \
0      [nan, nan, nan, nan, nan, nan, nan, nan]
1      [nan, nan, nan, nan, nan, nan, nan, nan]
2      [nan, nan, nan, nan, nan, nan, nan, nan]
3      [nan, nan, nan, nan, nan, nan, nan, nan]
4      [nan, nan, nan, nan, nan, nan, nan, nan]
...                                         ...
99995  [nan, nan, nan, nan, nan, nan, nan, nan]
99996  [nan, nan, nan, nan, nan, nan, nan, nan]
99997  [nan, nan, nan, nan, nan, nan, nan, nan]
99998  [nan, nan, nan, nan, nan, nan, nan, nan]
99999  [nan, nan, nan, nan, nan, nan, nan, nan]

                                                 photon0  \
0               [nan, nan, nan, nan, nan, nan, nan, nan]
1               [nan, nan, nan, nan, nan, nan, nan, nan]
2               [nan, nan, nan, nan, nan, nan, nan, nan]
3      ('photon', 0.777, 2.037, 62.69, 0.0, 0.0, 0.0,...
4               [nan, nan, nan, nan, nan, nan, nan, nan]
...                                                  ...

In [10]:
def unpacker(folder_data, new_folder_data):
    for nested_list in folder_data:
        if type(nested_list) == list:
            unpacker(nested_list, new_folder_data)
        else:
            new_folder_data.append(nested_list)
    folder_data = new_folder_data
    return folder_data

unpacked_dataframes = unpacker(folder_dataframes, [])
sample_num = np.min([len(dataframe.loc[:]) for dataframe in unpacked_dataframes])
print(sample_num)

folder_dataframes = [[dataframe.sample(n = sample_num) for dataframe in dataframes] for dataframes in folder_dataframes]

dataframe = unpacked_dataframes[0]
for row in dataframe.itertuples():
    print(row)

1000
Pandas(Index=19510, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', -1.626, 2.308, 93.36, 13.21, 8.0, 0.0, 8.59)", jet1="('jet', 1.228, -2.167, 73.99, 9.74, 11.0, 0.0, 0.0)", jet2="('jet', -1.55, -2.932, 71.19, 13.56, 6.0, 0.0, 3.28)", jet3="('jet', 0.271, -2.596, 60.32, 14.39, 9.0, 0.0, 0.41)", jet4="('jet', 2.591, -0.157, 43.07, 9.94, 4.0, 0.0, 1.02)", jet5="('jet', -2.519, 0.387, 24.05, 3.48, 3.0, 0.0, 0.0)", jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, -0.111, 28.95, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0="('tau', 0.361, 0.406, 112.61, 14.13, -1.0, 0.0, 0.42)", tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=17471, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', -2.916, 2.247, 80.37, 12.06, 0.0, 0.0, 7.3)", jet1="('jet', -2.915, -0.331, 45.44, 6.95, 0.0, 0.0, 1.63)", jet2="('jet', -3.046, -2.562, 44.86, 5.18, 0.0, 0.0, 22.35)", jet3="('jet', -1.868, -1.015, 39.92, 8.39, 7.0, 0.0, 1.27)", jet4="('jet', -1.112, 1.107, 31.78, 7.71, 10.0, 0.0, 999.9)", jet5='[nan, nan, nan, nan, nan, nan, nan, nan]', jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, -1.399, 25.77, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=11158, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', -0.483, -1.815, 117.44, 21.79, 12.0, 0.0, 1.17)", jet1="('jet', 0.6, 1.224, 94.93, 11.47, 3.0, 0.0, 1.36)", jet2="('jet', 0.785, -2.462, 78.27, 7.43, 5.0, 1.0, 1.74)", jet3="('jet', 0.606, -0.605, 62.39, 8.68, 5.0, 1.0, 1.39)", jet4="('jet', -0.395, 1.195, 37.69, 6.54, 5.0, 0.0, 6.05)", jet5='[nan, nan, nan, nan, nan, nan, nan, nan]', jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, 1.787, 52.24, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=9713, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', -0.882, -2.747, 88.08, 7.06, 2.0, 0.0, 15.25)", jet1="('jet', -0.615, 2.003, 59.08, 12.51, 12.0, 1.0, 0.0)", jet2="('jet', -0.098, 0.83, 54.88, 9.14, 7.0, 0.0, 0.34)", jet3="('jet', -1.708, -1.395, 50.98, 11.07, 6.0, 0.0, 0.35)", jet4="('jet', -0.329, -1.088, 48.37, 7.05, 8.0, 0.0, 0.0)", jet5='[nan, nan, nan, nan, nan, nan, nan, nan]', jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, 0.797, 30.21, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=89874, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', -2.596, 2.054, 168.9, 19.07, 1.0, 0.0, 10.39)", jet1="('jet', 1.472, -1.63, 90.91, 13.91, 12.0, 1.0, 0.83)", jet2="('jet', 3.865, -1.099, 78.36, 8.9, 0.0, 0.0, 7.4)", jet3="('jet', 1.499, -0.329, 55.52, 11.32, 8.0, 0.0, 2.08)", jet4="('jet', -3.59, 1.554, 52.5, 11.99, 0.0, 0.0, 1.76)", jet5="('jet', 4.088, 0.214, 38.73, 1.25, 0.0, 0.0, 11.41)", jet6="('jet', 2.798, 1.358, 35.87, 7.01, 0.0, 0.0, 0.64)", jet7="('jet', 2.437, 0.145, 30.2, 1.9, 1.0, 0.0, 0.1)", jet8="('jet', 1.842, -2.723, 23.41, 5.24, 6.0, 0.0, 1.3)", jet9="('jet', 2.311, -2.253, 22.71, 3.37, 4.0, 0.0, 0.0)", jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, -2.271, 76.4, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=75153, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', 1.18, 2.062, 153.78, 28.35, 10.0, 0.0, 5.41)", jet1="('jet', 1.936, -1.016, 58.52, 10.77, 8.0, 0.0, 0.59)", jet2="('jet', 0.547, 1.438, 52.27, 5.35, 4.0, 0.0, 0.29)", jet3="('jet', 1.841, 1.501, 37.82, 8.58, 12.0, 0.0, 0.87)", jet4='[nan, nan, nan, nan, nan, nan, nan, nan]', jet5='[nan, nan, nan, nan, nan, nan, nan, nan]', jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, -1.527, 54.6, 0.0, 0.0, 0.0, 0.0)", muon0="('muon', 0.477, -1.133, 112.57, 0.11, -1.0, 3.0, 115.0)", muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=27224, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', -0.902, 2.575, 78.65, 9.93, 8.0, 0.0, 0.55)", jet1="('jet', -1.241, -0.41, 64.95, 15.73, 9.0, 0.0, 0.64)", jet2="('jet', -2.558, 0.884, 63.1, 5.49, 1.0, 0.0, 3.36)", jet3="('jet', -2.985, 3.047, 39.03, 9.44, 0.0, 0.0, 5.84)", jet4="('jet', -2.478, -1.366, 33.67, 5.41, 4.0, 0.0, 26.72)", jet5='[nan, nan, nan, nan, nan, nan, nan, nan]', jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, -1.826, 20.55, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=83169, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', -1.496, -2.935, 88.46, 11.35, 9.0, 1.0, 1.55)", jet1="('jet', 0.048, 0.439, 85.85, 21.66, 25.0, 0.0, 1.59)", jet2="('jet', -1.456, 1.779, 74.93, 13.37, 9.0, 0.0, 0.3)", jet3="('jet', -0.203, 1.188, 58.77, 10.63, 12.0, 0.0, 3.1)", jet4="('jet', 0.141, -1.275, 52.4, 8.02, 5.0, 0.0, 6.3)", jet5="('jet', -0.4, 3.099, 49.27, 8.99, 5.0, 0.0, 3.1)", jet6="('jet', -1.095, -1.085, 48.74, 9.88, 8.0, 0.0, 0.87)", jet7="('jet', -2.526, 0.422, 22.9, 6.15, 5.0, 0.0, 999.9)", jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, -0.89, 27.25, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=46392, electron0="('electron', 0.651, 1.756, 82.99, 0.0, 1.0, 0.0, 0.0)", electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', 2.047, -0.829, 179.61, 17.68, 14.0, 1.0, 1.43)", jet1="('jet', -1.864, 1.965, 119.86, 20.71, 17.0, 0.0, 1.19)", jet2="('jet', 0.767, -2.035, 112.64, 14.52, 7.0, 0.0, 0.11)", jet3="('jet', 1.807, 0.379, 48.86, 12.83, 6.0, 0.0, 3.35)", jet4="('jet', -0.424, -1.958, 45.36, 13.97, 8.0, 0.0, 0.0)", jet5="('jet', 0.697, -0.156, 44.94, 5.36, 5.0, 1.0, 0.0)", jet6="('jet', 1.64, -3.121, 40.29, 9.09, 4.0, 0.0, 0.91)", jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, 2.239, 84.34, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=1614, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', -0.681, -2.972, 209.02, 16.91, 12.0, 0.0, 0.12)", jet1="('jet', -0.32, 0.375, 89.43, 14.65, 14.0, 0.0, 0.0)", jet2="('jet', -0.268, -0.339, 78.31, 12.98, 12.0, 1.0, 0.46)", jet3="('jet', -0.25, -1.088, 56.05, 8.95, 5.0, 0.0, 0.39)", jet4="('jet', 0.518, -0.72, 43.21, 4.95, 7.0, 1.0, 5.26)", jet5="('jet', 0.042, 1.201, 39.89, 11.76, 8.0, 0.0, 0.0)", jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, 1.088, 44.65, 0.0, 0.0, 0.0, 0.0)", muon0="('muon', -0.238, 2.395, 42.54, 0.11, 1.0, 2.0, 45.17)", muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=37143, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', 0.907, 2.955, 225.86, 23.66, 19.0, 0.0, 4.03)", jet1="('jet', 1.755, 0.392, 146.23, 16.57, 13.0, 1.0, 0.68)", jet2="('jet', 0.778, -2.618, 95.34, 20.52, 13.0, 0.0, 9.26)", jet3="('jet', -0.059, 2.945, 86.26, 9.74, 7.0, 1.0, 0.68)", jet4="('jet', 0.969, -0.033, 78.7, 9.51, 2.0, 1.0, 1.04)", jet5="('jet', 2.025, -0.167, 73.13, 9.05, 6.0, 0.0, 1.02)", jet6="('jet', -2.635, -1.397, 37.31, 9.51, 4.0, 0.0, 14.0)", jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, 0.058, 90.2, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=99769, electron0="('electron', 1.367, 0.842, 40.05, 0.0, 1.0, 0.0, 0.0)", electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', 0.605, 0.366, 70.7, 8.89, 7.0, 0.0, 2.17)", jet1="('jet', 0.114, -2.643, 53.86, 13.82, 11.0, 1.0, 0.79)", jet2="('jet', 0.547, 2.958, 29.14, 6.01, 5.0, 0.0, 0.0)", jet3='[nan, nan, nan, nan, nan, nan, nan, nan]', jet4='[nan, nan, nan, nan, nan, nan, nan, nan]', jet5='[nan, nan, nan, nan, nan, nan, nan, nan]', jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, -2.281, 24.28, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=76858, electron0="('electron', -0.725, 0.287, 62.21, 0.0, -1.0, 0.0, 0.0)", electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', -0.308, 2.678, 104.09, 7.2, 6.0, 0.0, 0.0)", jet1="('jet', -0.089, -1.053, 64.92, 11.97, 10.0, 0.0, 2.56)", jet2="('jet', 0.549, -2.795, 61.39, 9.92, 8.0, 1.0, 1.54)", jet3="('jet', -1.874, -0.233, 38.57, 7.92, 7.0, 1.0, 9.15)", jet4="('jet', -0.64, -0.899, 37.29, 5.99, 9.0, 0.0, 0.0)", jet5='[nan, nan, nan, nan, nan, nan, nan, nan]', jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, 1.277, 55.46, 0.0, 0.0, 0.0, 0.0)", muon0='[nan, nan, nan, nan, nan, nan, nan, nan]', muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)
Pandas(Index=84512, electron0='[nan, nan, nan, nan, nan, nan, nan, nan]', electron1='[nan, nan, nan, nan, nan, nan, nan, nan]', jet0="('jet', 1.208, -2.454, 110.75, 11.06, 4.0, 0.0, 1.71)", jet1="('jet', -0.461, 1.064, 81.13, 16.31, 10.0, 1.0, 0.27)", jet2="('jet', -0.491, -0.993, 39.33, 7.68, 7.0, 0.0, 0.0)", jet3="('jet', 0.016, 0.668, 36.99, 5.58, 7.0, 0.0, 999.9)", jet4="('jet', 0.728, 1.832, 26.31, 6.93, 4.0, 1.0, 1.03)", jet5='[nan, nan, nan, nan, nan, nan, nan, nan]', jet6='[nan, nan, nan, nan, nan, nan, nan, nan]', jet7='[nan, nan, nan, nan, nan, nan, nan, nan]', jet8='[nan, nan, nan, nan, nan, nan, nan, nan]', jet9='[nan, nan, nan, nan, nan, nan, nan, nan]', jet10='[nan, nan, nan, nan, nan, nan, nan, nan]', jet11='[nan, nan, nan, nan, nan, nan, nan, nan]', jet12='[nan, nan, nan, nan, nan, nan, nan, nan]', jet13='[nan, nan, nan, nan, nan, nan, nan, nan]', jet14='[nan, nan, nan, nan, nan, nan, nan, nan]', MET0="('MET', 0.0, -1.957, 46.8, 0.0, 0.0, 0.0, 0.0)", muon0="('muon', -0.457, 0.015, 42.36, 0.11, -1.0, 5.0, 44.0)", muon1='[nan, nan, nan, nan, nan, nan, nan, nan]', muon2='[nan, nan, nan, nan, nan, nan, nan, nan]', photon0='[nan, nan, nan, nan, nan, nan, nan, nan]', photon1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau0='[nan, nan, nan, nan, nan, nan, nan, nan]', tau1='[nan, nan, nan, nan, nan, nan, nan, nan]', tau2='[nan, nan, nan, nan, nan, nan, nan, nan]', datasets=0)

In [8]:
def input_data(event):
    pt_index = 3
    name_index = 0
    ptmax = sorted(event, key = lambda x: x[pt_index])[-1][pt_index]
    stuff_amount = len(event)
    try:
        met = [particle for particle in event if particle[name_index] == "MET"][0][pt_index]
    except:
        print(event)
    input_list = [ptmax, stuff_amount, met]
    
    return input_list

def dataframe_calc(dataframe):
    dataframe = dataframe.drop("datasets", axis = 1)
    dataframe_dict = {}
    events = [row for row in dataframe.itertuples(index = False)]
    for event_index, event in enumerate(events):
        event = [particle for particle in event if "nan" not in particle]
        dataframe_dict[event_index] = input_data(event)
    input_variables = ["ptmax", "stuff_amount", "met"]
    data_df = list(dataframe_dict.values())
    dataframe = pd.DataFrame(data_df, columns = input_variables)
    return dataframe


for dataframe in unpacker(folder_dataframes, []):
    dataframe_calc(dataframe)




# datasets = pd.concat([dataframe["datasets"] for dataframe in unpacker(folder_dataframes, [])])
# model_data = pd.concat([dataframe_calc(dataframe) for dataframe in unpacker(folder_dataframes, [])])

["('jet', -0.436, 0.886, 101.0, 10.33, 3.0, 0.0, 3.97)", "('jet', 0.036, -0.963, 56.53, 6.22, 4.0, 0.0, 13.9)", "('jet', -0.786, -2.108, 48.68, 7.62, 7.0, 1.0, 5.6)", "('MET', 0.0, 0.181, 31.61, 0.0, 0.0, 0.0, 0.0)", "('photon', -1.329, 2.482, 21.21, 0.0, 0.0, 0.0, 0.0)", "('tau', 1.549, -2.692, 68.36, 10.45, 1.0, 0.0, 0.56)"]

UnboundLocalError: local variable 'met' referenced before assignment